name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Acessa a pasta do projeto
            cd /home/ubuntu/aws-epidemiology-medallion-lake
            
            # Baixa as ultimas atualizacoes do GitHub
            # Como usamos volumes no docker-compose, os arquivos em streamlit_app
            # atualizam em tempo real dentro do container! Nao precisa de rebuild.
            git pull origin master
